### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by nsmag** [runnables/line-bot-sdk-nodejs#11]

**Comment by PanJ** [comment]
Have you tried `npm install --save-dev`? The dependencies have been modified as per https://github.com/runnables/line-bot-sdk-nodejs/commit/ca5bdb7cb03b43940a11dc7f8836d75438afbb26

**Comment by soraxtend** [comment]
@5un  Can you take a look on this issue?

**Comment by nsmag** [comment]
Fixed. See c19d72a7cdc108ca2384bf1d75b4f3aa22e7b35a.
