### ISSUE TITLE
few questions of EchoBot example

### ISSUE THREAD

**Issue by kennedy0527** [runnables/line-bot-sdk-nodejs#14]
I just try to run the EchoBot example 

and I couldn't understand how LINE BOT work .. 

in the code, I just changed channel ID, secret and mid to my bot account

then I just use my personal line to add my bot and send message to it

as your code, if I send 'me' to bot , it will reply 'Hi!, you're myname', right?

but actually it is nothing happen ....

Im sure the server is running and I also set callback url in the manage site 

callback url has to be SSL Certificate, so I just make a self-certificate for it ..

maybe this is where the problem occurred ?!!

thanks for helping me

**Comment by nsmag** [comment]
@kennedy0527: As mentioned in [the document](https://developers.line.me/bot-api/getting-started-with-bot-api-trial#register_callback_url)

"Note: The SSL certificate must be issued by an authorized CA ( see [authorized CA list](https://developers.line.me/wp-content/uploads/2016/04/ca_root.txt)). If a self-issued SSL certificate is applied to your server, requests sent from the LINE platform will fail."

I think self-certificate SSL will not work.

**Comment by 5un** [comment]
Hi @kennedy0527 

As mentioned earlier, self signed SSL would not work. I recommend using [Heroku](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction) for a quick start (since you'll get SSL automatically).

**Comment by kennedy0527** [comment]
Hi, thanks for replying 

I tried Heroku and succeeded to create a Heroku App

I've already gotten SSL which is automatically generated by Heroku

but when I tried to fill up Callback URL, it said port is needed..

I can see which port I listen by using `heroku logs --tail`

but how can I connect it with port ?

`https://example.herokuapp.com:xxxx`

doesn't work

**Comment by 5un** [comment]
Hi @kennedy0527 

Somehow, the LINE admin interface requires that you put the number of port even though it's obvious that it's 443 (because we're using HTTPS). For example, I need to put https://example.com:443/ to get it work.

**Comment by kennedy0527** [comment]
Hi @5un 

thanks for helping 

it's now running properly
